openapi: 3.0.0
info:
  version: 1.0.0
  title: Hospital API
  description: >-
    can check the availability of the required blood group in blood banks and
    can place the order
  termsOfService: 'https://bloodcare.com/terms-of-use-hosted/'
  contact:
    name: blood care
    url: bloodcare.com
    email: bloodcare@gmail.com
  license:
    name: Bloodcare License
    url: 'http://Bloodcare.com'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/bloodCare/Hospital_API_OSA3/1.0.0'
  - description: SwaggerHub API Auto Mocking
    url: >-
      https://virtserver.swaggerhub.com/soad-project/blood_storage_API_OAS3.0/1.0.0
tags:
  - name: storage
    description: Access to storage Details of the required blood group in blood banks
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /storage/inventory:
    get:
      description: Returns required blood group storage details
      parameters:
        - name: city
          in: query
          required: true
          description: city of the blood banks whose storage details are required
          schema:
            type: string
            example: kakinada
        - name: state
          in: query
          required: true
          description: state of the blood banks whose storage details are required
          schema:
            type: string
            example: andhra pradesh
        - name: blood group
          in: query
          required: true
          description: blood group required
          schema:
            type: string
            example: B +ve
      responses:
        '200':
          description: >-
            Successful pull of required blood gropu storage details from blood
            banks
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    blood bank id:
                      description: >-
                        id of the blood bank in which the storage required blood
                        group is available
                      type: integer
                      example: 2
                    blood group:
                      type: string
                      example: B +ve
                    available units:
                      type: integer
                      example: 2
  /storage/order:
    post:
      description: Place an order for a required blood group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        '400':
          description: Invalid Order
  '/storage/order/{orderId}':
    get:
      tags:
        - storage
      description: Find purchase order by ID
      parameters:
        - name: orderId
          in: path
          description: ID of the order that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/order'
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        '400':
          description: Invalid ID supplied
          content: {}
        '404':
          description: Order not found
          content: {}
    delete:
      tags:
        - storage
      description: Delete purchase order by ID
      parameters:
        - name: orderId
          in: path
          description: ID of the order that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '400':
          description: Invalid ID supplied
          content: {}
        '404':
          description: Order not found
          content: {}
components:
  schemas:
    order:
      type: object
      properties:
        id:
          type: integer
          example: 4
        blood bank id:
          type: integer
          example: 1
        blood group:
          type: string
          example: B +ve
        units required:
          type: integer
          example: 2
        shipDate:
          type: string
          example: '2020-10-15T07:59:22.830Z'
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
